global:
  resolve_timeout: 5m

route:
  receiver: telegram

receivers:
  - name: telegram
    telegram_configs:
      - bot_token: "8758404695:AAGr8O82kvL0EzU5Jd6ZqbNvW3nVspa0uBA"
        chat_id: 1101883521
        parse_mode: HTML
        send_resolved: true
