- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true


- name: Install Node Exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Configure Node Exporter
  ansible.builtin.template:
    src: node_exporter.j2
    dest: /etc/default/prometheus-node-exporter
    owner: root
    group: root
    mode: '0644'
  notify: Restart Node Exporter

- name: Enable and start Node Exporter
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    state: started
    enabled: true
