- name: Check Node Exporter
  hosts: node_exporters
  become: true


  tasks:
    - name: Check Node Exporter service
      ansible.builtin.systemd:
        name: prometheus-node-exporter
        state: started
        enabled: true
