- name: Configure Node Exporter
  hosts: node_exporters
  become: true

  roles:
    - node_exporter


- name: Configure Prometheus
  hosts: prometheus_servers
  become: true

  roles:
    - prometheus 
