name: Ansible CI


on:
  push:
    branches:
      - main
      - ci
  pull_request:

jobs:
  ansible-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install ansible
        run: python -m pip install ansible-core


      - name: Install ansible-lint
        run: python -m pip install ansible-lint


      - name: Ansible syntax check
        working-directory: ansible
        run: ansible-playbook -i inventory/hosts.yml playbooks/site.yml --syntax-check


      - name: Run ansible-lint
        run: ansible-lint ansible
