name: Runner test

on:
  push:
    branches:
      - ci


jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Show hostname
        run: hostname

      - name: Show system
        run: uname -a
